import { useEffect, useState } from "react";
import { createPublicClient, createWalletClient, custom, http, parseAbi, type Address } from "viem";
import { createRoot } from "react-dom/client";
import "./styles.css";
const CONTRACT=(import.meta.env.VITE_CONTRACT_ADDRESS||"0x0000000000000000000000000000000000000000") as Address; const RPC=import.meta.env.VITE_RPC_URL||"https://studio.genlayer.com/api";
const abi=parseAbi(["function submit_observation(string,string,string)","function verify_observation(string) returns (string)","function get_receipt(string) view returns (string)"]); const client=createPublicClient({transport:http(RPC)});
function App(){const [account,setAccount]=useState<Address>();const[id,setId]=useState("");const[q,setQ]=useState("");const[url,setUrl]=useState("");const[receipt,setReceipt]=useState("");const[status,setStatus]=useState("Connect a wallet to begin.");
async function connect(){const eth=(window as any).ethereum;if(!eth)return setStatus("Install an EIP-1193 wallet.");const w=createWalletClient({transport:custom(eth)});const[a]=await w.requestAddresses();setAccount(a);setStatus(`Connected ${a.slice(0,6)}…${a.slice(-4)}`)}
async function write(method:"submit_observation"|"verify_observation",args:string[]){if(!account)return connect();const w=createWalletClient({account,transport:custom((window as any).ethereum)});setStatus("Sign in wallet; waiting for GenLayer finality…");const hash=await (w.writeContract as any)({address:CONTRACT,abi,functionName:method,args});await client.waitForTransactionReceipt({hash});setStatus(`Finalized ${hash.slice(0,12)}…`);read()}
async function read(){if(!id)return;try{setReceipt((await client.readContract({address:CONTRACT,abi,functionName:"get_receipt",args:[id]})) as string||"No receipt yet.")}catch{setReceipt("No receipt yet.")}}useEffect(()=>{read()},[id]);return <main><div className="eyebrow">GENLAYER · PROJECT</div><h1>Evidence<span>Atlas</span></h1><p className="lede">Durable observation receipts, bound to independently fetched evidence.</p><button onClick={connect}>{account?"Wallet connected":"Connect wallet"}</button><section><label>Receipt ID</label><input value={id} onChange={e=>setId(e.target.value.toUpperCase())} placeholder="EVENT-001"/><label>Question</label><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="What does the evidence establish?"/><label>Evidence URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/><div className="actions"><button onClick={()=>write("submit_observation",[id,q,url])}>Submit observation</button><button className="secondary" onClick={()=>write("verify_observation",[id])}>Verify with consensus</button></div></section><p className="status">{status}</p><pre>{receipt}</pre><small>Contract: {CONTRACT}</small></main>}
createRoot(document.getElementById("root")!).render(<App/>);
